import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from 'react';
//import AppSidebar from '../components/app-sidebar';
//import { SidebarProvider } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Student's Chatbot",
  description: "Generated by create-assistant-ui",
};

{/*
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { */}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full relative bg-transparent`}
      >
        <div className="relative z-10 min-h-svh">
        {/*children
        <div className="flex">
          <AppSidebar />
          <main className="flex-1">{children}</main>
        </div>
        

        <SidebarProvider>
          <div className="flex">
            <AppSidebar showFlow={false} />
            <main className="flex-1">{children}</main>
          </div>
        </SidebarProvider>
        */}
          {children}
        </div>
      </body>
    </html>
  );
}
