# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cccr-chat

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual

jobs:
  build-and-push:
    name: Build and push to ACR
    runs-on: [self-hosted,frontend]
    permissions:
      contents: read # actions/checkout
    
    env:
      ACR_NAME: "crcicddevkrc01-fdbpdsdjbrhudtg3"
      ACR_IMAGE_NAME: "chatbot-frontend"

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Login to Azure(Managed ID)'
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR using Azure CLI
        run: az acr login --name ${{ env.ACR_NAME }}

      # 고유 태그: 커밋 해시를 사용해 버전을 명확히 추적
      # 최신 태그: 'latest' 태그는 개발/테스트 환경에서 편리하게 사용
      - name: Set up Docker image tags
        run: |
          echo "IMAGE_TAG_UNIQUE=${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_TAG_LATEST=${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_IMAGE_NAME }}:latest" >> $GITHUB_ENV

      # 5. Dockerfile을 사용해 이미지 빌드 및 ACR로 푸시
      - name: Build and push Docker image to ACR
        run: |
          # 두 개의 태그로 이미지 빌드
          docker build . -t ${{ env.IMAGE_TAG_UNIQUE }} -t ${{ env.IMAGE_TAG_LATEST }}
          
          # 두 개의 태그 모두 푸시
          docker push ${{ env.IMAGE_TAG_UNIQUE }}
          docker push ${{ env.IMAGE_TAG_LATEST }}